version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_rails_app_development
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_rails_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
